In [2]:
import gymnasium as gym

### 一个实例代码（不完整）

In [14]:
import gymnasium as gym
env = gym.make("LunarLander-v2", render_mode="human")  # 初始化环境，参数-1为环境名称，参数-2为环境的交互方式
observation, info = env.reset(seed=42)                 # reset环境，理解为把环境重置在起点，并返回此时的observation(state?)  
for _ in range(1000):
   action = env.action_space.sample()                  # 这里设置自己的策略，就是怎么样去选取下一个动作。这里用了系统的随机采样方法。
   observation, reward, terminated, truncated, info = env.step(action)  # 采取动作，每个动作会带来新的state，以及reward，和各种信号。

   if terminated or truncated:                         # 如果终止或者到达timelimit，就停止进行。
      observation, info = env.reset()

env.close()

### 随机选取动作

In [44]:
env = gym.make('CartPole-v1', render_mode='human')
env.reset()

for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, done, truncated, info = env.step(action)  # 
    print(observation)
env.close()

[-0.02336011  0.24448277  0.02126328 -0.2794138 ]
[-0.01847046  0.04906404  0.015675    0.01989897]
[-0.01748918 -0.14627916  0.01607298  0.31748602]
[-0.02041476  0.04861022  0.0224227   0.02991498]
[-0.01944256  0.24340355  0.023021   -0.25560987]
[-0.01457448  0.04796062  0.0179088   0.04424445]
[-0.01361527  0.24282125  0.01879369 -0.24273472]
[-0.00875885  0.04743596  0.013939    0.05581648]
[-0.00781013  0.2423553   0.01505533 -0.2324362 ]
[-0.00296302  0.0470215   0.0104066   0.0649574 ]
[-0.00202259  0.24199271  0.01170575 -0.22442411]
[ 0.00281726  0.43694544  0.00721727 -0.51339173]
[ 0.01155617  0.24172257 -0.00305057 -0.21844321]
[ 0.01639062  0.436888   -0.00741943 -0.51208687]
[ 0.02512838  0.24187133 -0.01766117 -0.2217512 ]
[ 0.02996581  0.04700622 -0.02209619  0.06530877]
[ 0.03090593 -0.14779209 -0.02079002  0.35093915]
[ 0.02795009 -0.3426123  -0.01377123  0.6369945 ]
[ 0.02109785 -0.53753954 -0.00103134  0.925309  ]
[ 0.01034706 -0.73264754  0.01747484  1.2176676 ]


### 查看所有已注册好的环境

In [11]:
from gymnasium import envs
env_specs = envs.registry.keys()
envs_ids = [env_spec for env_spec in env_specs]
print(envs_ids)

['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'phys2d/CartPole-v0', 'phys2d/CartPole-v1', 'phys2d/Pendulum-v0', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v2', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'tabular/Blackjack-v0', 'tabular/CliffWalking-v0', 'Reacher-v2', 'Reacher-v4', 'Pusher-v2', 'Pusher-v4', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Humanoid-v2', 'Humanoid-v3', 'Humanoid-v4', 'HumanoidStandup-v2', 'HumanoidStandup-v4', 'GymV21Environment-v0', 'GymV26Environment-v0']


### MountainCar-v0 例子

In [18]:
env = gym.make('MountainCar-v0', render_mode = 'human')
print('观测空间 = {}'. format(env.observation_space))
print('动作空间 = {}'. format(env.action_space)) 
print('观测范围 = {} ~ {}'. format(env.observation_space.low,
env.observation_space.high))
print('动作数 = {}'. format(env.action_space.n))

# 观测空间表示，观测的状态有两个值，类型均为float，以及两个值的范围。
# 动作空间表示有离散的三个值。

观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测范围 = [-1.2  -0.07] ~ [0.6  0.07]
动作数 = 3


In [19]:
# 实现智能体来控制小车移动

class SimpleAgent:
    def __init__(self, env):
        pass

    def decide(self, observation):                # 决策
        position, velocity = observation          # obsevation的两维参数分别表示位置和动作。
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03, 0.3 * (position + 0.9) ** 4 - 0.008)
        ub = -0.07 * (position + 0.38) ** 2 + 0.07
        if lb < velocity < ub:                    # 设定速度的上下界
            action = 2
        else:
            action = 0
        return action         # 返回动作
    
    def learn(self, *args):   # 不确定传入参数的数量，*args以元组的形式传递参数。
        pass
        
agent = SimpleAgent(env)      # Agent是由策略类创造的

In [20]:
# 定义智能体与环境的交互

def play(env, agent, train=False):
    episode_reward = 0.                        # 记录回合总奖励，初始值为0
    observation, _ = env.reset(seed=3)            # 随机性的重置游戏新起始状态，开始新的回合
                                               # reset的返回值包括了obervation和info，这里记得要只取observation
    
    while True:                                # 不断循环，直到回合结束
        action = agent.decide(observation)     # 根据obervation信息执行动作
        next_observation, reward, done, _, _ = env.step(action) # 执行动作
        episode_reward += reward               # 收集回合奖励
        if train:                              # 判断是否训练智能体
            agent.learn(observation, action, reward, done) # 学习
        if done: # 回合结束，跳出循环
            break
        observation = next_observation
    
    return episode_reward # 返回回合总奖励

In [22]:
# 运行程序

env = gym.make('MountainCar-v0', render_mode = 'human')
episode_reward = play(env, agent)
print(f'总回合奖励 = {episode_reward}')

env.close() # 关闭图形界面

总回合奖励 = -105.0


In [23]:
# 测得10回合的平均奖励
import numpy as np

env = gym.make('MountainCar-v0', render_mode = 'human')
episode_rewards = [play(env, agent) for _ in range(10)]
print(f'平均回合奖励 = {np.mean(episode_rewards)}')

env.close() # 关闭图形界面

平均回合奖励 = -105.0
